language: node_js
node_js:
- node
cache:
  directories:
    - node_modules
install:
  - travis_retry npm install

script: 
    - npm install -g serverless
    - npm install -g serverless-webpack
    - serverless deploy -v  
    
    
    